sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t roronoazoro9695/multi-docker -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true roronoazoro9695/multi-docker npm run test

# after_success:
#   - docker build -t siddharthrajkumar/multi-client ./client
#   - docker build -t siddharthrajkumar/multi-nginx ./nginx
#   - docker build -t siddharthrajkumar/multi-server ./server
#   - docker build -t siddharthrajkumar/multi-worker ./worker

#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#   - docker push siddharthrajkumar/multi-client
#   - docker push siddharthrajkumar/multi-nginx
#   - docker push siddharthrajkumar/multi-server
#   - docker push siddharthrajkumar/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-south-1"
#   app: "multi-docker"
#   env: "Multi-docker-env"
#   bucket_name: "elasticbeanstalk-ap-south-1-839117473964"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
